# 本地开发数据库：H2
spring.datasource.url=jdbc:h2:file:./data/luca;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 自动更新本地数据库结构
spring.jpa.hibernate.ddl-auto=update

# 允许使用本地 H2 控制台
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console